### ISSUE TITLE
Sign Up UX / Error

### ISSUE THREAD

**Issue by FejZa** [InflexionPoint/ByldrFeedback#1]
Hi,

I tried signing up for the service on the website by selecting "BYLDR'S HALL". But the experience turned out to be confusing.

1. Select `BYLDR'S HALL` link on the website
2. Login mask appears
![screen_3](https://user-images.githubusercontent.com/9565734/90680521-432e4680-e262-11ea-873c-94a00cc11ee4.PNG)

3. Select `Sign Up` and enter data
![screen_1](https://user-images.githubusercontent.com/9565734/90680584-580ada00-e262-11ea-865a-76280da64d92.PNG)

4. There is now two buttons available `Sign Up` and `Log In`. `Log In` didn't seem to make sense to me as I was just about to sign up for the first time, so I selected `Sign Up`. But that lead to returning to the first screen with an error message displayed
![screen_2](https://user-images.githubusercontent.com/9565734/90680679-87b9e200-e262-11ea-8134-0561742caace.PNG)

5. I selected `Sign Up` again and entered my data again. This time I selected `Log In`. But that button would also just return to the first screen but this time no error is displayed.

6. Since no error was displayed I tried doing a log in but my user didn't exist so it seems it didn't get created.

7. Result: I can't sign up

I also the web portal address `http://167.172.210.177/signup` is displayed instead of a domain.

**Comment by mr0ng** [comment]
Thanks for reporting this @FejZa - looks to be a new issue that arose. We'll report back here when the bug is fixed.

**Comment by FejZa** [comment]
Thanks @mr0ng, I was able to sign up now and create an account. The UX was the same though. I did not get any hint that the creation was succesful. I just tried afterwards and was able to login.

**Comment by mr0ng** [comment]
Thanks @FejZa I split out that feedback as a separate issue and will close this one. Thanks for testing.
