### ISSUE TITLE
[HL2] Adding simple 3D object is not working

### ISSUE THREAD

**Issue by dudziakl** [InflexionPoint/ByldrFeedback#10]
I tried to add simple cube, sphere, or import a chair from the library. For all cases created object was too small to do anything with it. I couldn't resize, rotate or move it. I was also surprised that the object was created on the floor instead in the air in front of me. 
![obraz](https://user-images.githubusercontent.com/12583808/92218430-69c2c300-ee99-11ea-8807-0f24db6e8d27.png)
Here is the full video: 
https://1drv.ms/v/s!AlNnUgY45UWZkN9L1GfdSJPJKrEVsQ?e=cJEDgh

**Comment by mr0ng** [comment]
Thanks @dudziakl . This issue was related to ARM64 builds on HoloLens 2 and has been fixed in our Alpha 2 release. We'll update you when the release is ready for testing.

**Comment by mr0ng** [comment]
I will close this issue once Alpha 2 is available to testers

**Comment by mr0ng** [comment]
Fixed in https://github.com/InflexionPoint/ByldrFeedback/releases/tag/Beta1
