### ISSUE TITLE
Uploading GLTF Files

### ISSUE THREAD

**Issue by sealotus94** [InflexionPoint/ByldrFeedback#102]
Hey there, I'm trying to upload some 3D GLTF models from Sketchfab and this error keeps occurring: 
I'm not sure what I could do? 
![image](https://user-images.githubusercontent.com/31398243/107280841-7803a500-6a1e-11eb-9630-ec7ddeacc48e.png)

**Comment by mr0ng** [comment]
@sealotus94 we removed support for GLTF files since there were many issues. You can now upload either .glb or .fbx files. Any questions let us know.
