### ISSUE TITLE
Feedback in Lobby area (UX/UI)

### ISSUE THREAD

**Issue by sealotus94** [InflexionPoint/ByldrFeedback#104]
This is more of a UX/UI thing, I was hoping/wondering if team could add in hover states (or something like that) to the "Recent Bylds" in the lobby area? Similar to how the "Project Menu" and "Create" buttons change color, I think it would be nice to show a little feedback for users in lobby area. 
![image](https://user-images.githubusercontent.com/31398243/107717218-b5736700-6c98-11eb-8482-fd2141c86074.png)

I appreciate how Create Menu Icons let me know I'm gonna touch it: 
![image](https://user-images.githubusercontent.com/31398243/107717107-70e7cb80-6c98-11eb-9ed2-0498d8549ddd.png)

**Comment by mr0ng** [comment]
Issue fixed and tested in build 501. Should be available soon on public channels
