### ISSUE TITLE
Bing maps coordinates and address entry doesnt allow backspacing

### ISSUE THREAD

**Issue by gregrady** [InflexionPoint/ByldrFeedback#106]
The user cannot delete their inputs or preset values when entering in coordinates, addresses, or changing any value in the bing maps settings.

**Comment by s4t0** [comment]
Hi @gregrady, we appreciate the feedback. this should be fixed in the [Beta V2.1 release](https://github.com/InflexionPoint/ByldrFeedback/releases/tag/v0.2.2-beta.2), let me know if the issue persists after upgrading to the new build.
