### ISSUE TITLE
A "See and select all objects in scene" button would be appreciated

### ISSUE THREAD

**Issue by gregrady** [InflexionPoint/ByldrFeedback#108]
When making a few buttons and menus, I lost them as I couldn't see or interact with them after coming out of preview mode. Having an option on the first menu that lets you see and select the objects and highlight them would help a lot as bylds get more complicated.

**Comment by s4t0** [comment]
Hi @gregrady thanks for the feedback. On the wrist menu, you should see a button to open the hierarchy menu which will allow you to do find and select objects by name. Let me know if this is what you are looking for.

**Comment by mr0ng** [comment]
I believe @s4t0 has pointed out the solution to this issue. If there are any additional concerns, feel free to open a new issue or re-open this and clarify as needed
