### ISSUE TITLE
Missing points indicators

### ISSUE THREAD

**Issue by gregrady** [InflexionPoint/ByldrFeedback#110]
https://user-images.githubusercontent.com/61300265/109344166-fe4c2380-7833-11eb-8f8b-40aee1577d04.mp4

The points that are attached to the fingers have gone missing on my version. Had to restart the app to fix the issue.
I attached a 10 second video of the problem.

**Comment by mr0ng** [comment]
Thanks Greg. This issue appears to have been resolved in the latest version of Byldr. If you find this issue is persisting, let us know.
