### ISSUE TITLE
Load a previous version of a byld due to crash

### ISSUE THREAD

**Issue by gregrady** [InflexionPoint/ByldrFeedback#112]
I'm attempting to build something and it has 18 objects (some cloned and the rest are individual models) it ended up crashing the whole build to the point that I have to get rid of it and start over. The main menu no longer works on the left hand and only some objects are visible.

https://user-images.githubusercontent.com/61300265/109403121-c969ca80-7920-11eb-85c9-3451e27af802.mp4

**Comment by mr0ng** [comment]
This is now fixed and will be available in the next version of Byldr
