### ISSUE TITLE
[Bug] Skybox can bee seen

### ISSUE THREAD

**Issue by Acimaz** [InflexionPoint/ByldrFeedback#16]
On the login page you can see the skybox as seen in the screenshot:

![Visible_Skybox](https://user-images.githubusercontent.com/3418387/98096104-9db36800-1e8b-11eb-8f5e-06a8f2eb94c1.jpg)

**Comment by s4t0** [comment]
@mr0ng this appears to have been fixed, can we close this issue?

**Comment by mr0ng** [comment]
Fix confirmed internally. Will be available in Beta 2 release.
