### ISSUE TITLE
[Bug] Changing hand material

### ISSUE THREAD

**Issue by Acimaz** [InflexionPoint/ByldrFeedback#19]
Hand material is changing in login when turning hand palm to face:

![Changed_Hand_Material](https://user-images.githubusercontent.com/3418387/98096431-0ac6fd80-1e8c-11eb-9d0e-347c6d194790.jpg)

**Comment by mr0ng** [comment]
tested on Quest 2 and confirmed working. Will be in Beta 2 release.
