### ISSUE TITLE
Hands (Hand Tracking) show up but no pointers available

### ISSUE THREAD

**Issue by FejZa** [InflexionPoint/ByldrFeedback#2]
On Oculus Quest hands did show up when using hand tracking but there were no pointers attached to them and I couldn't use them for interaction at all.

**Comment by mr0ng** [comment]
@FejZa this issue has now been fixed in Beta 1! You can download the latest version from SideQuest: https://sidequestvr.com/app/1971/byldr

Or our release page: https://github.com/InflexionPoint/ByldrFeedback/releases/tag/Beta1
