### ISSUE TITLE
[Bug] Create Menu position

### ISSUE THREAD

**Issue by Acimaz** [InflexionPoint/ByldrFeedback#28]
When opening the create menu and then pressing the preview button and then trying to access the create menu again results in the behavior shown in the picture, the object menu stays where the player was before he pressed the preview button.

![Selected_Object_Menu_Far_Away](https://user-images.githubusercontent.com/3418387/98097909-eec45b80-1e8d-11eb-9bf3-019692a2b5de.jpg)

**Comment by s4t0** [comment]
@mr0ng it looks like this is the same as #85

**Comment by mr0ng** [comment]
Fix confirmed internally. Will be available in Beta 2 release.
