### ISSUE TITLE
Environment scale does not fit

### ISSUE THREAD

**Issue by FejZa** [InflexionPoint/ByldrFeedback#3]
In the empty room scene the scaling did not fit and broke the immersion. I felt tiny standing next to the door. When standing my head wouldn't even reach the door handle.

**Comment by mr0ng** [comment]
@FejZa is this feedback that the room scene is too big?

**Comment by FejZa** [comment]
Yes. The room felt huge to me. I used the door as a point of reference.

**Comment by skyzdev** [comment]
Sean, this issue should be closed. I fixed the door size a few weeks ago.
