### ISSUE TITLE
[Bug] Wrong tool tip message

### ISSUE THREAD

**Issue by Acimaz** [InflexionPoint/ByldrFeedback#37]
The voice trigger tooltip is wrong (it shows the tool tip for animation end):

![Voice_Button_Wrong_Tooltip](https://user-images.githubusercontent.com/3418387/98098741-03552380-1e8f-11eb-9436-a8dd17dfc647.jpg)

**Comment by mr0ng** [comment]
Fix confirmed internally. Will be available in Beta 2 release.
