### ISSUE TITLE
Object menu appears far away

### ISSUE THREAD

**Issue by FejZa** [InflexionPoint/ByldrFeedback#4]
Steps to reproduce:

1. Teleport to a location
2. Place an object
3. Teleport to some other location further away
4. Select the object in distance
5. -> The menu appears way too far away for interaction

**Comment by mr0ng** [comment]
Great feedback, thank you.

**Comment by s4t0** [comment]
@mr0ng this looks to be the same issue as #85

**Comment by mr0ng** [comment]
Fix confirmed internally. Will be available in Beta 2 release.
