### ISSUE TITLE
[Bug] Text manipulator and text position do not match

### ISSUE THREAD

**Issue by Acimaz** [InflexionPoint/ByldrFeedback#46]
The text object and the actual text are not at the same position which makes it nearly impossible to position a text correctly:

![Text_Manipulator_And_Text_Not_Same_Position](https://user-images.githubusercontent.com/3418387/98100124-b8d4a680-1e90-11eb-8a02-d0101c408a8e.jpg)

**Comment by mr0ng** [comment]
Tested and working internally. Will be available via public channels soon.
