### ISSUE TITLE
[Bug] Can't remove web api panel

### ISSUE THREAD

**Issue by Acimaz** [InflexionPoint/ByldrFeedback#56]
After the web API UI is placed you can't select and remove it again.

**Comment by skyzdev** [comment]
Please select the top bar of the Web API panel in Byld mode. Then you should be able to delete from the Options menu.

**Comment by Acimaz** [comment]
Alright, I think this is related to https://github.com/InflexionPoint/ByldrFeedback/issues/23 then

**Comment by mr0ng** [comment]
Fix confirmed internally. Will be available in Beta 2 release.
