### ISSUE TITLE
[Bug] Menu panel rotation

### ISSUE THREAD

**Issue by Acimaz** [InflexionPoint/ByldrFeedback#62]
The rotation of panels around their forward axis is not desirable:

![Menus_Not_Billboarding](https://user-images.githubusercontent.com/3418387/98101551-ab202080-1e92-11eb-8b32-aed0d11a5951.jpg)

**Comment by Acimaz** [comment]
https://github.com/InflexionPoint/ByldrFeedback/issues/31 should fix this with a Z-axis rotation constraint.

**Comment by mr0ng** [comment]
Fix confirmed internally. Will be available in Beta 2 release.
