### ISSUE TITLE
[HL2] App is not saving user credentials or even login 

### ISSUE THREAD

**Issue by dudziakl** [InflexionPoint/ByldrFeedback#7]
Each time when I open the app I have to repeat my login and password. As app is very unstable this is very inconvenient. It could be nice to have "keep logged-in" check box.

**Comment by mr0ng** [comment]
Good feedback. Noted and we will consider as part of ongoing updates.

**Comment by mr0ng** [comment]
@dudziakl this has been fixed and will be available in Alpha 2

**Comment by mr0ng** [comment]
Fixed in Beta1: https://github.com/InflexionPoint/ByldrFeedback/releases/tag/Beta1
