### ISSUE TITLE
[Bug]Created a situations when object material or texture was broken

### ISSUE THREAD

**Issue by HoloKalasha666** [InflexionPoint/ByldrFeedback#76]
Add action "on/off" to the object and trigger "when selected". After recreating this action in Preview mode and then return to project editing the object had a strange transparent texture.
![1605014884960](https://user-images.githubusercontent.com/74252066/98793922-2cd2f980-2411-11eb-83fc-d30d0800bf27.jpg)

**Comment by mr0ng** [comment]
Fix is currently being tested internally

**Comment by mr0ng** [comment]
Fix confirmed, to be included with Beta 2 release
