### ISSUE TITLE
[HL2] Native HoloLens keyboard is appearing during the login view

### ISSUE THREAD

**Issue by dudziakl** [InflexionPoint/ByldrFeedback#8]
There are two keyboards visible (mrtk and native) during login. Mrtk keyboard is displayed behind login panel that make it not usable or it is sometimes blocking access to password field (!!!). Password field should have an option to display as plain text because it is hard to write with a finger and find a typoo. 

![20200904_094300_HoloLens](https://user-images.githubusercontent.com/12583808/92215844-aee4f600-ee95-11ea-8f86-27fd2f22e90f.jpg)

**Comment by mr0ng** [comment]
Feedback noted. We will remove the Byldr keyboard on HL2 and keep the native keyboard.

**Comment by mr0ng** [comment]
@dudziakl this has been fixed and will be available in Alpha 2

**Comment by mr0ng** [comment]
Fixed in https://github.com/InflexionPoint/ByldrFeedback/releases/tag/Beta1
