### ISSUE TITLE
[BUG] Sometimes UI gets unresponsive. Input ray is not shown.

### ISSUE THREAD

**Issue by decea89** [InflexionPoint/ByldrFeedback#84]
This time I had to go back to home and re-enter to my scene to be able to use the input properly.

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/15913221/99692894-15d47d00-2a8b-11eb-85b3-49b0a83fc38b.gif)

**Comment by Tiger-Cross** [comment]
Can confirm, I sometimes get this as well but for me it flickers rather than disappears completely. I don't need to leave the scene to fix it, I just need to move my hands past an object that I've placed. I'm on the Quest 2 device

**Comment by mr0ng** [comment]
Fix confirmed internally. Will be available in Beta 2 release.
