### ISSUE TITLE
[BUG?] work panel doesn't follow to user after teleporting

### ISSUE THREAD

**Issue by decea89** [InflexionPoint/ByldrFeedback#85]
If I start working with a certain work panel and then I use the teleport feature to change my position, when I try to go back to work I realize that the work panel keeps placed at the previous position. Far from my current position. This is a strange behaviour and it feels uncomfortable.

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/15913221/99694431-b8413000-2a8c-11eb-8198-2182bb9e8c9a.gif)

**Comment by s4t0** [comment]
this has been fixed and will be in the next build
