### ISSUE TITLE
[Bug] Issues with primitive shape copies that had a picture material

### ISSUE THREAD

**Issue by sealotus94** [InflexionPoint/ByldrFeedback#88]
All I had on the shape was that I resized it to what is in the picture, and then added a picture texture. Later I grouped it, and found that when I copied it to reuse in another spot underneath another asset it wasn't going under. It would appear on top even though I would place it directly beneath the shape on top.
![com InflexionPoint Byldr-20201121-143057](https://user-images.githubusercontent.com/31398243/99887919-016cbd80-2c0e-11eb-88c4-df14ff43ff4c.jpg)
![image](https://user-images.githubusercontent.com/31398243/99887955-45f85900-2c0e-11eb-88e7-cf8e61ef7317.png)
![image](https://user-images.githubusercontent.com/31398243/99888105-acca4200-2c0f-11eb-94e2-34bc2fe8671e.png)

**Comment by mr0ng** [comment]
Fix confirmed, to be included with Beta 2 release
