### ISSUE TITLE
[UI/UX Request] Back Button inconsistency

### ISSUE THREAD

**Issue by sealotus94** [InflexionPoint/ByldrFeedback#91]
Throughout some of the items in Project Menu, the back button is inconsistent. I'd recommend placing it at the top or keeping at side because I already have to bend my neck farther down in order to get the entire menu in view. 
Also, what if it changed from a word to an icon? A back arrow?? 
https://uofh-my.sharepoint.com/:v:/g/personal/emgomez4_cougarnet_uh_edu/EX4cunDxv6FKgdzI-H_rCeIBJVFNZ6wUR3kIZxUTtU60FA?e=vjbxD9

**Comment by s4t0** [comment]
this has been changed and will be in the next build
