### ISSUE TITLE
[Bug] Renaming uploaded asset to library breaks import on Quest 2

### ISSUE THREAD

**Issue by Tiger-Cross** [InflexionPoint/ByldrFeedback#94]
I tried to rename an image in my asset library on my laptop. After doing so, none of my images were imported to the app on my Quest 2. I resolved the error by deleting the renamed images from my library on the portal. I'm assuming this is just an uncaught error somewhere (but I may be wrong). :)

**Comment by mr0ng** [comment]
I believe this issue has been fixed, but may need more in-depth testing. We are unable to reproduce this error after updating some thumbnail-related fixes on our web portal. Please test again upon release of Beta 2.
