### ISSUE TITLE
[Feature Request] Unable to move/teleport during preview mode on Quest 2

### ISSUE THREAD

**Issue by Tiger-Cross** [InflexionPoint/ByldrFeedback#97]
I noticed that when selecting preview, the user is teleported to the starting location and is unable to move through the environment (on my Quest 2 device). It would be useful to have this enabled for the preview so that the user can explore the environment.

**Comment by s4t0** [comment]
Hi @Tiger-Cross, by default teleporting is disabled in preview mode but you can enable it in the byld options. Hand Menu > Settings > Options > Teleport toggle. Let me know if enabling that fixes the issues you are having.

**Comment by Tiger-Cross** [comment]
Ah you are right. I apologise I was toggling the wrong teleport option! Thanks!
