### ISSUE TITLE
Text does not appear in text box on Quest 2

### ISSUE THREAD

**Issue by Tiger-Cross** [InflexionPoint/ByldrFeedback#98]
When selecting [create -> text] a text box is summoned. However, I experience two issues with this on my Quest 2 headset.

1. If I've teleported, the keyboard to enter the text appears where I first spawned in the scene (so I have to move it around or teleport back to it to enter the text)
2. (most important issue) The text doesn't appear inside the textbox, depending on where it is positioned, the text appears translated somewhat.

**Comment by s4t0** [comment]
this is the same as #46
